## Colors configuration
[colors.primary]
background = "#000000"
foreground = "#fdf6e3"

[colors.normal]
black   = "#263640"
red     = "#ec7875"
green   = "#61c766"
yellow  = "#fdd835"
blue    = "#42a5f5"
magenta = "#ba68c8"
cyan    = "#4dd0e1"
white   = "#bfbaac"

[colors.bright]
black   = "#4a697d"
red     = "#fb8784"
green   = "#70d675"
yellow  = "#ffe744"
blue    = "#51b4ff"
magenta = "#c979d7"
cyan    = "#5cdff0"
white   = "#fdf6e3"
